all: ex1 ex2

ex1: ex1_filedescriptors.cpp
	g++ -std=c++17 -pedantic -Wall -Wextra -o ex1 ex1_filedescriptors.cpp

ex2: ex2_stackcorruption.cpp
	g++ -std=c++17 -pedantic -Wall -Wextra -o ex2 ex2_stackcorruption.cpp
	
clean:
	rm ex1 ex2